version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Budapest
    open-pull-requests-limit: 10
    groups:
      production-minor-and-patch:
        dependency-type: production
        update-types:
          - minor
          - patch
      development-minor-and-patch:
        dependency-type: development
        update-types:
          - minor
          - patch
      eslint-major:
        patterns:
          - eslint
          - "@eslint/js"
        update-types:
          - major
      vite-major:
        patterns:
          - vite
          - "@sveltejs/vite-plugin-svelte"
        update-types:
          - major
      vitest-major:
        patterns:
          - vitest
          - "@vitest/*"
        update-types:
          - major
    commit-message:
      prefix: deps

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Budapest
    commit-message:
      prefix: deps(docker)
    ignore:
      - dependency-name: node
        update-types:
          - version-update:semver-major

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Budapest
    groups:
      actions-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    commit-message:
      prefix: ci
